---
# This playbook installs Java and Solr to Debian hosts and then uploads custom Solr configuration files.

- name: Install Java and Solr
  hosts: solr
  vars_files:
    - "./group_vars/solr.yaml"
  pre_tasks:
  - include_tasks: pre_tasks/apt_update.yaml
  roles:
    # installs java 17
    - role: geerlingguy.java
      become: yes
    
    # installs solr
    - role: geerlingguy.solr
      become: yes # was required
      solr_cores: [] # please do not create any cores yourself
      solr_create_user: yes # creates an os user for solr
      solr_user: solr
      solr_group: solr
      solr_version: "9.2.1"
      solr_service_manage: true
      solr_service_name: solr
      solr_service_state: started
      solr_install_dir: /opt
      solr_install_path: /opt/solr #solr executable is here
      #solr_home: "{{solr_home}}" #index data is here. See https://stackoverflow.com/questions/21738661/ansible-recursive-loop-detected-in-template-string
      solr_port: "8983"
      solr_xms: "512M" #t2.micro has a little less than 1g
      solr_xmx: "512M"
      solr_timezone: "UTC"
      solr_opts: "$SOLR_OPTS -Dlog4j2.formatMsgNoLookups=true" #nice to be able to set solr opts here
      solr_restart_handler_enabled: true #"restart solr" command makes solr restart
      #Note: if you're building containers or AMIs, you might need to disable the restart handler for a provisioning run.
  post_tasks:
    - include_tasks: ../common-tasks/create-folders-for-core-configs.yaml
    - include_tasks: ../common-tasks/copy-config-files.yaml
